t1 <- read.csv("ACCESS_na.csv", as.is=TRUE)

t2 <- read.csv("ACSAT_na.csv", as.is=TRUE)
t3 <- read.csv("AGSUB_na.csv", as.is=TRUE)
t4 <- read.csv("AZE_na.csv", as.is=TRUE)
t5 <- read.csv("CHMORT_na.csv", as.is=TRUE)
t6 <- read.csv("CO2GDP_na.csv", as.is=TRUE)
t7 <- read.csv("CO2KWH_na.csv", as.is=TRUE)
t8 <- read.csv("FORCH_na.csv", as.is=TRUE)
t9 <- read.csv("FSOC_na.csv", as.is=TRUE)
t10 <- read.csv("HAP_na.csv", as.is=TRUE)
t11 <- read.csv("MPAEEZ_na.csv", as.is=TRUE)
t12 <- read.csv("PACOVD_na.csv", as.is=TRUE)
t13 <- read.csv("PACOVW_na.csv", as.is=TRUE)
t14 <- read.csv("PM25EXBL_na.csv", as.is=TRUE)
t15 <- read.csv("PM25_na.csv", as.is=TRUE)
t16 <- read.csv("POPSIGRAT_na.csv", as.is=TRUE)
t17 <- read.csv("POPS_na.csv", as.is=TRUE)
#t18 <- read.csv("POPS_orig_na.csv", as.is=TRUE)
t19 <- read.csv("TCEEZ_na.csv", as.is=TRUE)
t20 <- read.csv("WASTECXN_na.csv", as.is=TRUE)
t21 <- read.csv("WATSUP_na.csv", as.is=TRUE)

merged <- merge(t1, t2, by=c("code", "iso", "country"))
merged <- merge(merged, t3, by=c("code", "iso", "country"))
merged <- merge(merged, t4, by=c("code", "iso", "country"))
merged <- merge(merged, t5, by=c("code", "iso", "country"))
merged <- merge(merged, t6, by=c("code", "iso", "country"))
merged <- merge(merged, t7, by=c("code", "iso", "country"))
merged <- merge(merged, t8, by=c("code", "iso", "country"))
merged <- merge(merged, t9, by=c("code", "iso", "country"))
merged <- merge(merged, t10, by=c("code", "iso", "country"))
merged <- merge(merged, t11, by=c("code", "iso", "country"))
merged <- merge(merged, t12, by=c("code", "iso", "country"))
merged <- merge(merged, t13, by=c("code", "iso", "country"))
merged <- merge(merged, t14, by=c("code", "iso", "country"))
merged <- merge(merged, t15, by=c("code", "iso", "country"))
merged <- merge(merged, t16, by=c("code", "iso", "country"))
merged <- merge(merged, t17, by=c("code", "iso", "country"))
#merged <- merge(merged, t18, by=c("code", "iso", "country"))
merged <- merge(merged, t19, by=c("code", "iso", "country"))
merged <- merge(merged, t20, by=c("code", "iso", "country"))
merged <- merge(merged, t21, by=c("code", "iso", "country"))
merged <- merged[order(merged$country),]
head(merged)
write.csv(merged, "indicators.csv", row.names=FALSE)


x <- read.csv("indicators.csv", as.is=TRUE)
names(x[,4:6])
names(x[,7:28])
names(x[,29:85])
names(x[,86:88])
names(x[,89:111])
names(x[,112:132])
names(x[,133:153])
names(x[,154])
names(x[,155:216])
names(x[,217:219])
names(x[,220:242])
names(x[,243:265])
names(x[,266:288])
names(x[,289:301])
names(x[,302:314])
names(x[,315:326])
names(x[,327:384])
names(x[,385:441])
names(x[,442])
names(x[,443:464])
